//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WisdomWellServer.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WISDOMWELLSERVER_DIALOG     102
#define IDR_MAINFRAME                   128
#define IDD_EMPLOYEE                    129
#define IDD_SETTINGDLG                  130
#define IDR_MAINMENU                    131
#define IDD_LOGINDLG                    134
#define IDD_SYS_LOG                     135
#define IDD_SAMPLINGDLG                 136
#define IDD_CAR_RECORDDLG               137
#define IDD_MODIFYDLG                   139
#define IDI_ICON1                       140
#define IDB_BITMAP1                     141
#define IDB_BITMAP2                     143
#define IDB_BITMAP5                     149
#define IDB_BITMAP6                     150
#define IDI_ICON2                       151
#define IDI_ICON3                       153
#define IDC_USERNAME                    1000
#define IDC_UPASSWORD                   1001
#define IDC_EDITVERIFY                  1002
#define IDC_SAFEWEIGHT                  1003
#define IDC_PASSWORD                    1004
#define IDC_BTNOK                       1004
#define IDC_TIMEDIFF                    1005
#define IDC_LSTCAR                      1005
#define IDC_VMECHINE                    1006
#define IDC_BTNCANCEL                   1006
#define IDC_BTN_OK                      1007
#define IDC_REALTIME_HOUR               1008
#define IDC_BTNLEAVE                    1009
#define IDC_REALTIME_MIN                1009
#define IDC_EDITNAME                    1010
#define IDC_REALTIME_SEC                1010
#define IDC_TIMEMORONHOUR               1011
#define IDC_EDITSTATUS                  1012
#define IDC_TIMEMORONMIN                1012
#define IDC_BTNRECORD                   1013
#define IDC_TIMEMOROFFHOUR              1013
#define IDC_LISTCARDRECORD              1014
#define IDC_TIMEMOROFFMIN               1014
#define IDC_TIMEAFTONHOUR               1015
#define IDC_BTNSEARCHCARD               1016
#define IDC_TIMEAFTONMIN                1016
#define IDC_CURRDATE                    1017
#define IDC_TIMEAFTOFFHOUR              1019
#define IDC_DEVICESTATUSGROUP           1020
#define IDC_TIMEAFTOFFMIN               1020
#define IDC_POSITIONGROUP               1021
#define IDC_BTN_CANCEL                  1021
#define IDC_NOWCARWEIGHT                1022
#define IDC_CARDIRECT                   1023
#define IDC_CARSTATUS                   1024
#define IDC_NOWTIME                     1025
#define IDC_NOWWORKSTATUS               1026
#define IDC_CARSpeed                    1027
#define IDC_REALTEMPERATURE             1028
#define IDC_REALHUMIDITY                1029
#define IDC_REALCONCENTRATION           1030
#define IDC_DAILYYIELD                  1031
#define IDC_AVGYIELD                    1032
#define IDC_EMPTOTAL                    1033
#define IDC_EMPSHOULDBE                 1034
#define IDC_EMPCURRENT                  1035
#define IDC_EMPABSENCE                  1036
#define IDC_EMPLEAVE                    1037
#define IDC_EDITSEARCHBYNAME            1038
#define IDC_NOWCARSPEED                 1038
#define IDC_EDITSEARCHBYNUM             1039
#define IDC_CARDIRECT2                  1039
#define IDC_BTNSEARCH                   1040
#define IDC_CARArea0                    1040
#define IDC_LISTEMPLOYEEVIEW            1041
#define IDC_CARArea1                    1041
#define IDC_EDITNUM                     1042
#define IDC_CARArea2                    1042
#define IDC_EDITAGE                     1043
#define IDC_CARArea3                    1043
#define IDC_EDITSEX                     1044
#define IDC_CARArea4                    1044
#define IDC_BTNDELETE                   1045
#define IDC_SafeDoor0                   1045
#define IDC_BTNMODIFY                   1046
#define IDC_SafeDoor1                   1046
#define IDC_BTNADD                      1047
#define IDC_SafeDoor2                   1047
#define IDC_DAILY                       1048
#define IDC_SafeDoor3                   1048
#define IDC_DURING                      1049
#define IDC_SafeDoor4                   1049
#define IDC_REALTIME                    1050
#define IDC_SafeDoor5                   1050
#define IDC_WORKTIME                    1051
#define IDC_NOWCARSPEED2                1051
#define IDC_SafeDoor6                   1052
#define IDC_CrossingStatus              1052
#define IDC_SEPERATOR                   1053
#define IDC_EMPCROSS                    1053
#define IDC_MSCOMM                      1054
#define IDC_BTN_TEST_COMM               1055
#define IDC_MAXTEMP                     1056
#define IDC_MAXGAS                      1057
#define IDC_PHONENUM                    1058
#define IDC_CHKTIME                     1060
#define IDC_DPSTART                     1061
#define IDC_DPEND                       1062
#define IDC_LSTSYSLOG                   1063
#define IDC_ERRCODE                     1064
#define IDC_ERRRESON                    1065
#define IDC_ERRDEAL                     1066
#define IDC_EDITSTART                   1067
#define IDC_EDITEND                     1068
#define IDC_LSTSAMPLING                 1069
#define IDC_STCTIME                     1070
#define IDC_STCTEMP                     1071
#define IDC_STCWE                       1072
#define IDC_STCGAS                      1073
#define IDC_STCAVGTEMP                  1074
#define IDC_STCAVEWE                    1075
#define IDC_STCAVGGAS                   1076
#define IDC_STCYWEIGHT                  1077
#define IDC_STCWEIGHT                   1078
#define IDC_STCTOTALWEIGHT              1079
#define IDC_STCCARNUM                   1080
#define IDC_STCAVEYWEIGHT               1081
#define IDC_STCAVGWEIGHT                1082
#define IDC_VERIFY                      1083
#define IDC_NEWUSERNAME                 1084
#define IDC_NEWPASSWORD                 1085
#define IDC_SUREPASSWORD                1086
#define IDC_STATIC_1                    1088
#define IDC_STATIC_2                    1089
#define IDC_STATIC_3                    1090
#define IDM_MODIFY_PASSWD               32773
#define IDM_PARAM_SETTING               32774
#define IDM_ABOUT                       32776
#define IDM_SYS_LOG                     32777
#define IDM_SAMPLING_RECORD             32778
#define IDM_CARRECORD                   32779
#define IDM_MGR_EMPLOYEE                32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
